---
# files: 'directory1/directory2'

# Which of these should have stages?

default_install_hook_types:
    - commit-msg
    - prepare-commit-msg
    - pre-commit
    - pre-merge-commit
    - pre-push
    - pre-rebase
    - post-checkout
    - post-commit
    - post-merge
    - post-rewrite

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          # General
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-toml
          - id: check-xml
          - id: check-yaml
          - id: detect-private-key
          - id: double-quote-string-fixer
          - id: end-of-file-fixer
          - id: fix-byte-order-marker
          - id: mixed-line-ending # Replaces or checks mixed line ending.
          - id: trailing-whitespace
          - id: no-commit-to-branch # Protect specific branches from direct checkins.
            # Both master and main are protected by default if no branch argument is set.
            # args: [--branch, master, --branch, develop]

          # Json
          - id: check-json
          - id: pretty-format-json # Checks that all your JSON files are pretty.

          # Python
          - id: check-ast # Check whether files parse as valid python.
          - id: check-builtin-literals # Require literal syntax when initializing empty or zero Python builtin types.
          - id: check-docstring-first
          - id: debug-statements # Check for debugger imports and py37+ breakpoint() calls in python source.
          - id: name-tests-test # Assert that files in tests/ end in _test.py, or optionally test*.py
          - id: requirements-txt-fixer

    # General

    - repo: https://github.com/lycheeverse/lychee.git
      rev: v0.15.1
      hooks:
          - id: lychee
          # Optionally include additional CLI arguments
          # args: ["--no-progress", "--exclude", "file://"]

    - repo: https://github.com/sirosen/texthooks
      rev: 0.6.7
      hooks:
          - id: fix-smartquotes
          - id: fix-ligatures

    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v4.0.0-alpha.8
      hooks:
          - id: prettier
            stages: [pre-commit]

    # Ansible

    - repo: https://github.com/ansible-community/ansible-lint.git
      rev: v24.9.2
      hooks:
          - id: ansible-lint
            stages:
                - pre-commit
                - pre-push

    # Docker

    - repo: https://github.com/IamTheFij/docker-pre-commit
      rev: v3.0.1
      hooks:
          - id: docker-compose-check

    - repo: https://github.com/pryorda/dockerfilelint-precommit-hooks
      rev: v0.1.0
      hooks:
          - id: dockerfilelint
            stages: [pre-commit]

    - repo: https://github.com/hadolint/hadolint
      rev: v2.13.1-beta
      hooks:
          - id: hadolint

    # Git

    - repo: https://github.com/jorisroovers/gitlint
      rev: v0.19.1
      hooks:
          - id: gitlint

    - repo: https://github.com/commitizen-tools/commitizen
      rev: v3.29.1
      hooks:
          - id: commitizen
            stages: [commit-msg]

    # Python

    - repo: https://github.com/econchick/interrogate
      rev: 1.7.0
      hooks:
          - id: interrogate
            args:
                - --verbose

    - repo: https://github.com/ikamensh/flynt/
      rev: "1.0.1"
      hooks:
          - id: flynt

    - repo: https://github.com/asottile/blacken-docs
      rev: 1.19.0
      hooks:
          - id: blacken-docs

    - repo: https://github.com/dosisod/refurb
      rev: v2.0.0
      hooks:
          - id: refurb

    - repo: https://github.com/HunterMcGushion/docstr_coverage
      rev: v2.3.2
      hooks:
          - id: docstr-coverage
            args: ["--verbose", "4", "."]
            always_run: false

    - repo: https://github.com/MarcoGorelli/auto-walrus
      rev: 0.3.4
      hooks:
          - id: auto-walrus

    - repo: https://github.com/RobertCraigie/pyright-python
      rev: v1.1.385
      hooks:
          - id: pyright

    - repo: https://github.com/asottile/add-trailing-comma
      rev: v3.1.0
      hooks:
          - id: add-trailing-comma
            args:
                - --py36-plus

    - repo: https://github.com/PyCQA/bandit
      rev: 1.7.10
      hooks:
          - id: bandit

    - repo: https://github.com/asottile/dead
      rev: v1.5.2
      hooks:
          - id: dead

    - repo: https://github.com/jendrikseipp/vulture
      rev: v2.13
      hooks:
          - id: vulture

    - repo: https://github.com/hadialqattan/pycln
      rev: v2.4.0 # Possible releases: https://github.com/hadialqattan/pycln/releases
      hooks:
          - id: pycln

    - repo: https://github.com/MarcoGorelli/absolufy-imports
      rev: v0.3.1
      hooks:
          - id: absolufy-imports

    - repo: https://github.com/pre-commit/pygrep-hooks
      rev: v1.10.0
      hooks:
          - id: python-check-blanket-noqa
          - id: python-check-blanket-type-ignore
          - id: python-check-mock-methods
          - id: python-no-eval
          - id: python-no-log-warn
          - id: python-use-type-annotations
          - id: rst-backticks
          - id: rst-directive-colons
          - id: rst-inline-touching-normal
          - id: text-unicode-replacement-char

    - repo: https://gitlab.com/smop/pre-commit-hooks
      rev: v1.0.0
      hooks:
          - id: check-poetry # Validates the structure of the pyproject.toml file.

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.12.0
      hooks:
          - id: mypy

    - repo: https://github.com/jazzband/pip-tools
      rev: 7.4.1
      hooks:
          - id: pip-compile
            files: ^requirements/production\.(in|txt)$
            args: [requirements/production.in]

    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: "v0.7.0"
      hooks:
          - id: ruff
            args: [--fix, --force-exclude, --exit-non-zero-on-fix]
            types_or: [python, pyi, jupyter] # Run on notebooks too.
          - id: ruff-format
            types_or: [python, pyi, jupyter] # Run on notebooks too.

    # YAML

    - repo: https://github.com/adrienverge/yamllint
      rev: v1.35.1
      hooks:
          - id: yamllint
            args: [-c=.yamllint.yml]

    # SQL

    - repo: https://github.com/sqlfluff/sqlfluff
      rev: 3.2.4
      hooks:
          - id: sqlfluff-lint
          # For dbt projects, this installs the dbt "extras".
          # You will need to select the relevant dbt adapter for your dialect
          # (https://docs.getdbt.com/docs/available-adapters):
          # additional_dependencies: ['<dbt-adapter>', 'sqlfluff-templater-dbt']
          - id: sqlfluff-fix
          # Arbitrary arguments to show an example
          # args: [--rules, "L003,L014"]
          # additional_dependencies: ['<dbt-adapter>', 'sqlfluff-templater-dbt']

    # Mixed

    - repo: https://github.com/kraymer/cesar
      rev: v1.0.0
      hooks:
          - id: cesar

    - repo: https://github.com/jumanjihouse/pre-commit-hooks
      rev: 3.0.0
      hooks:
          # - id: bundler-audit  # FIXME: Fix ruby hooks
          # - id: check-mailmap
          # - id: fasterer
          # - id: forbid-binary
          # - id: git-check  # Configure in .gitattributes
          # - id: git-dirty  # Configure in .gitignore
          # - id: markdownlint  # Configure in .mdlrc
          # - id: reek
          # - id: require-ascii
          # - id: rubocop
          - id: script-must-have-extension
          - id: script-must-not-have-extension
          - id: shellcheck
            args: [--external-sources, --format=gcc, --shell=bash]
          - id: shfmt

    - repo: https://github.com/Lucas-C/pre-commit-hooks
      rev: v1.5.5
      hooks:
          - id: remove-crlf
          - id: remove-tabs
            exclude: .git/COMMIT_EDITMSG

    - repo: https://github.com/sirosen/check-jsonschema
      rev: 0.29.4
      hooks:
          - id: check-github-actions
          - id: check-github-workflows
          - id: check-readthedocs

    - repo: https://github.com/zricethezav/gitleaks
      rev: v8.21.1
      hooks:
          - id: gitleaks

    - repo: https://github.com/rhysd/actionlint
      rev: v1.7.3
      hooks:
          - id: actionlint

    - repo: https://github.com/MarcoGorelli/cython-lint
      rev: v0.16.2
      hooks:
          - id: cython-lint

    - repo: https://github.com/lycheeverse/lychee.git
      rev: v0.15.1
      hooks:
          - id: lychee
          # Optionally include additional CLI arguments
          # args: ["--no-progress", "--exclude", "file://"]

